# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Robert Edwards
title: Senior Software Engineer (Mobile iOS)
email: rcedwards@gmail.com
website: https://rcedwards.github.io

# Social links
github_username:  rcedwards
linkedin_username: roberted
# twitter_username: facespics
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Robert Edwards a senior software engineer specializing in iOS mobile development.

# I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: Hobbies
more_content: | # this will include new lines to allow paragraphs
  
# Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   # - Rock climbing
   # - Gaming
   # - Knitting
   # - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
